### PR TITLE
global: move all functionality from inspire-next

### PR DESCRIPTION
**Pull request by david-caro**
This first commit just aims to create a module with which we can
replace all dojson code from inspire-next. No refactoring is being
done except when necessary to pass the tests.

Signed-off-by: David Caro <david@dcaro.es>

### CODE REVIEW

**Comment by jacquerie** [comment]
This is destroying `git` history. Not only is `git` history valuable by itself, but it is even more valuable in `dojson`, as it has been built as a data-driven project that converged to the "best" solution by successive approximation and refinement.

Also, it is quite unfair to credit yourself for stuff you didn't write.

**Comment by david-caro** [comment]
Would it be enough if I mention it in the commit message? About the history, it's still in the inspire-next repo, that will never go away, if it's so relevant for you to have it here, I can add a file with the git log from there or something.

**Comment by jacquerie** [comment]
No, since there exists a way to preserve history: https://stackoverflow.com/q/1365541/374865.

**Comment by david-caro** [comment]
That does not look easy, nice nor really useful imo...
Will try though, see what comes out, when I have some time.

**Comment by jacquerie** [comment]
> That does not look easy, nice nor really useful imo...

I disagree, but even if I'd agree it would still be the **fair** thing to do. Would it please you to see your name wiped from the history of your projects at Red Hat because someone didn't find it convenient to keep a record of your contributions?

**Comment by david-caro** [comment]
Giving credit in the README, LICENSE, AUTHORS, the header of the file, the commit message or anywhere is fair enough for me, though I'd agree that I'm not very prideful.

On the fun side, I actually lost all my contributions according to github xd, as I used the work email for the commits...

And mentioning the original repo removes the need to import the whole git history of the tree from the old repo, that will not go away, and will still keep it intact, where you can dig up the original contributions (that were actually made to that repo, not this, so imo it's even more accurate).

Anyhow, you being one of the authors and seeing that it matters to you I'll check it out.

**Comment by david-caro** [comment]
I'll try to remove myself from the committer for the old commits... looking

**Comment by david-caro** [comment]
Hmm... having a different history entry point messes up the PR (github closes it)

**Comment by david-caro** [comment]
I've opened #2 ... it seems I can't reopen this one.

**Pull request closed without merging**
