### PR TITLE
documents: prefer original_url for json->marc

### PR DESCRIPTION
**Pull request by david-caro**
Signed-off-by: David Caro <david@dcaro.es>

### CODE REVIEW

**Comment by david-caro** [comment]
Because legacy is not able to handle authentication to labs, so it can't really download from there.

**Comment by david-caro** [comment]
An alternative is to put there the path on eos.

**Comment by david-caro** [comment]
But, dojson does not know at this point.

**Comment by michamos** [comment]
it can, https://github.com/inspirehep/invenio/commit/4986ed09ca8734545fa58145d10d20dfa26e91a3

**Comment by david-caro** [comment]
then it's not working :/  
```
     "error_message": "   Stage 2 failed: ERROR: while elaborating FFT tags: Error when downloading http://labs.inspirehep.net/api/files/74a5fc4f-b922-4107-93e1-0e1dea1bff88/fulltext.pdf into /opt/cds-invenio/var/tmp/bibdocfile_6ciS2b.pdf: http://labs.inspirehep.net/api/files/74a5fc4f-b922-4107-93e1-0e1dea1bff88/fulltext.pdf seems to be empty", 
```

**Comment by kaplun** [comment]
Mmh. I checked with @jacquerie live and indeed legacy is right here... The downloaded file is really empty and legacy fails early in order to underline systematic errors.

**Comment by david-caro** [comment]
In this case, the file was empty (or so it looked). So I redownloaded it, then it was not empty anymore:
```
build1$ ll /opt/inspire/var/data/workflows/files/0e/47/b8c5-deaf-40a7-9089-6f8037728499/data
-rw-r--r-- 1 aoeu def-cg 771000 Nov 17 16:24 /opt/inspire/var/data/workflows/files/0e/47/b8c5-deaf-40a7-9089-6f8037728499/data

04:31 PM env:inspire_production_to_deploy <venv:inspire>~ 
build1$ head /opt/inspire/var/data/workflows/files/0e/47/b8c5-deaf-40a7-9089-6f8037728499/data
%PDF-1.5
%����
1 0 obj
<</Type/Catalog/Pages 2 0 R/Lang(en-GB) /StructTreeRoot 114 0 R/MarkInfo<</Marked true>>>>
endobj
2 0 obj
<</Type/Pages/Count 12/Kids[ 3 0 R 19 0 R 29 0 R 38 0 R 47 0 R 48 0 R 49 0 R 50 0 R 51 0 R 52 0 R 57 0 R 111 0 R] >>
endobj
3 0 obj
<</Type/Page/Parent 2 0 R/Resources<</Font<</F1 5 0 R/F2 11 0 R/F3 13 0 R/F4 15 0 R/F5 17 0 R>>/ExtGState<</GS7 7 0 R/GS8 8 0 R>>/XObject<</Image9 9 0 R>>/ProcSet[/PDF/Text/ImageB/ImageC/ImageI] >>/MediaBox[ 0 0 595.32 841.92] /Contents 4 0 R/Group<</Type/Group/S/Transparency/CS/DeviceRGB>>/Tabs/S/StructParents 0>>
```
but from the web node's perspective...
```
web1$ ll /opt/inspire/var/data/workflows/files/0e/47/b8c5-deaf-40a7-9089-6f8037728499/data
-rw-r--r-- 1 aoeu def-cg 0 Nov 17 16:24 /opt/inspire/var/data/workflows/files/0e/47/b8c5-deaf-40a7-9089-6f8037728499/data

web1$ head /opt/inspire/var/data/workflows/files/0e/47/b8c5-deaf-40a7-9089-6f8037728499/data
web1$
```

So it looks like eos is doing nasty stuff 😢

**Comment by jacquerie** [comment]
I don't dislike the idea of trying the `original_url` if the Labs one failed, though... can it be implemented on Legacy?

CC: @kaplun

**Comment by kaplun** [comment]
That's a bit adding a strong bias towards labs. I.e.:
if download fails:
    if record comes from labs (which we recognize thanks to?):
        fetch from URL in 8564...

I like it... :joy:

**Pull request closed without merging**
